spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vehicleMarketplaceSpring
    username: admin
    password: 19941993
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
server:
  port: 8081